version: '3.4'

services:
  db:
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    expose:
      - "5432"

  backend:
    image: private-routes-backend:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "8080"
    depends_on:
      - db
    healthcheck:
      test: wget --spider 0.0.0.0:8080/actuator/health

  frontend:
    image: private-routes-frontend:latest
    ports:
      - "80:80"
    healthcheck:
      test: curl -f 0.0.0.0:80/healthy
    depends_on:
      - backend 
      - services

  services:
    image: privacy-services:latest
    expose: 
      - "5000"
